--- # Playbook demo of debug and register statement
- hosts: dbserver
  remote_user: vagrant
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: no
  tasks:
  - name: Installing telnet pkg
    apt: 
      name: telnet
      state: latest
    register: result
  - debug: var=result
