---
- hosts: webserver
  remote_user: vagrant
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes
  tasks:
   - name: Install web components
     apt: name={{item}} state=present update_cache=yes
     with_items:
      - apache2
      - python-pip
      - python-virtualenv
     
   - name: Ensure apache2 started
     service: name=apache2 state=started enabled=yes
   
 
   - name: Ensure mod_wsgi enabled
     apache2_module: state=present name=wsgi 
     notify: restart apache2 
  
   - name: copy demo app source
     copy: src=vagrant@192.168.135.10/demo/app/ dest=vagrant@192.168.135.111/var/www/demo mode=0755
     notify: restart apache2

   - name: apche virtual host vonfig
     copy: src=demo/app.cfg  dest=/etc/apache2/site-available mode=0755
     notify: restart apache2

  handlers:
   - name: restart apache2
     service: name=apache2 state=restartd


